#!/usr/bin/env bash

USER="michaelbennett99"

if [[ $# -ne 1 ]]; then
    echo "Usage: $(basename $0) <directory ssh url>"
    exit 1
fi

# Clone git repository
git clone $1

# Get directory name
filename=$(basename $1)
name=${filename%%.*}

echo $filename
echo $name

gh repo create $name --private

cd $name

git remote set-url origin "git@github.com:$USER/$name.git"

git push -u origin main
